import 'dart:io';
import 'package:flutter/material.dart';
import 'package:trackai/features/home/ai-options/service/filedownload.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  print('Testing download functionality...');

  // Test permission check
  print('Checking storage permission...');
  bool hasPermission = await FileDownloadService.hasStoragePermission();
  print('Has storage permission: $hasPermission');

  if (!hasPermission) {
    print('Requesting storage permission...');
    hasPermission = await FileDownloadService.requestStoragePermission();
    print('Permission granted: $hasPermission');
  }

  if (hasPermission) {
    // Test download functionality
    print('Testing file download...');
    try {
      String testContent =
          '''
AI Workout Plan - Test Plan

Generated on: ${DateTime.now()}

This is a test workout plan to verify the download functionality.

Workout Details:
- Duration: 7 Days
- Type: Strength Training
- Level: Intermediate

Day 1: Upper Body
- Push-ups: 3 sets x 10 reps
- Pull-ups: 3 sets x 5 reps
- Bench Press: 3 sets x 8 reps

Day 2: Lower Body
- Squats: 3 sets x 12 reps
- Deadlifts: 3 sets x 8 reps
- Lunges: 3 sets x 10 reps each leg

Day 3: Rest Day
- Light stretching and recovery

Day 4: Cardio
- Running: 30 minutes
- Cycling: 20 minutes

Day 5: Full Body
- Burpees: 3 sets x 10 reps
- Mountain climbers: 3 sets x 20 reps
- Plank: 3 sets x 30 seconds

Day 6: Rest Day
- Light walking and stretching

Day 7: Active Recovery
- Yoga or swimming

Tips:
- Stay hydrated throughout your workouts
- Listen to your body and rest when needed
- Gradually increase intensity
- Maintain proper form for all exercises

Generated by TrackAI Smart Gym Kit
''';

      String? filePath = await FileDownloadService.downloadWorkoutPlan(
        testContent,
        'Test_Workout_Plan',
      );

      if (filePath != null) {
        print('✅ File downloaded successfully!');
        print('File path: $filePath');

        // Verify file exists
        File file = File(filePath);
        if (await file.exists()) {
          print('✅ File exists and is accessible');
          print('File size: ${await file.length()} bytes');
        } else {
          print('❌ File does not exist');
        }
      } else {
        print('❌ File download failed');
      }
    } catch (e) {
      print('❌ Error during download test: $e');
    }
  } else {
    print('❌ Cannot test download without storage permission');
  }

  print('Download functionality test completed.');
}
