// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYqOwI_7MQ-Pfz5BcKinqKZO-fzLXxWdA',
    appId: '1:45963215599:web:412687d40ef729d8b6911a',
    messagingSenderId: '45963215599',
    projectId: 'trackai-5f380',
    authDomain: 'trackai-5f380.firebaseapp.com',
    storageBucket: 'trackai-5f380.firebasestorage.app',
    measurementId: 'G-XCMXG9BNJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITJk6TvH7KPNABHcFEr81k146wZOaQTk',
    appId: '1:45963215599:android:c15b19578391d0e6b6911a',
    messagingSenderId: '45963215599',
    projectId: 'trackai-5f380',
    storageBucket: 'trackai-5f380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZARVYbhzF6LqqCF7TGdaJLoCFXXzlG6E',
    appId: '1:45963215599:ios:3e4252f6db90ea34b6911a',
    messagingSenderId: '45963215599',
    projectId: 'trackai-5f380',
    storageBucket: 'trackai-5f380.firebasestorage.app',
    iosBundleId: 'com.example.trackai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZARVYbhzF6LqqCF7TGdaJLoCFXXzlG6E',
    appId: '1:45963215599:ios:3e4252f6db90ea34b6911a',
    messagingSenderId: '45963215599',
    projectId: 'trackai-5f380',
    storageBucket: 'trackai-5f380.firebasestorage.app',
    iosBundleId: 'com.example.trackai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYqOwI_7MQ-Pfz5BcKinqKZO-fzLXxWdA',
    appId: '1:45963215599:web:842eb9007226448ab6911a',
    messagingSenderId: '45963215599',
    projectId: 'trackai-5f380',
    authDomain: 'trackai-5f380.firebaseapp.com',
    storageBucket: 'trackai-5f380.firebasestorage.app',
    measurementId: 'G-15S5PY1Q03',
  );
}
